// cartConstants.js

export const CART_ADD_REQUEST = 'CART_ADD_REQUEST';
export const CART_ADD_SUCCESS = 'CART_ADD_SUCCESS';
export const CART_ADD_FAIL = 'CART_ADD_FAIL';

export const CART_DELETE_REQUEST = 'CART_DELETE_REQUEST';
export const CART_DELETE_SUCCESS = 'CART_DELETE_SUCCESS';
export const CART_DELETE_FAIL = 'CART_DELETE_FAIL';

export const CART_UPDATE_REQUEST = 'CART_UPDATE_REQUEST';
export const CART_UPDATE_SUCCESS = 'CART_UPDATE_SUCCESS';
export const CART_UPDATE_FAIL = 'CART_UPDATE_FAIL';

export const CART_DECREASE_REQUEST = 'CART_DECREASE_REQUEST';
export const CART_DECREASE_SUCCESS = 'CART_DECREASE_SUCCESS';
export const CART_DECREASE_FAIL = 'CART_DECREASE_FAIL';

export const CART_PRODUCTS_REQUEST = 'CART_PRODUCTS_REQUEST';
export const CART_PRODUCTS_SUCCESS = 'CART_PRODUCTS_SUCCESS';
export const CART_PRODUCTS_FAIL = 'CART_PRODUCTS_FAIL';

export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST';
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
export const CHECKOUT_FAIL = 'CHECKOUT_FAIL';

export const GET_TOTAL_PRODUCTS_REQUEST = 'GET_TOTAL_PRODUCTS_REQUEST';
export const GET_TOTAL_PRODUCTS_SUCCESS = 'GET_TOTAL_PRODUCTS_SUCCESS';
export const GET_TOTAL_PRODUCTS_FAIL = 'GET_TOTAL_PRODUCTS_FAIL';

