export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAIL = 'ADD_COMMENT_FAIL';

export const GET_ALL_COMMENTS_REQUEST = 'GET_ALL_COMMENTS_REQUEST';
export const GET_ALL_COMMENTS_SUCCESS = 'GET_ALL_COMMENTS_SUCCESS';
export const GET_ALL_COMMENTS_FAIL = 'GET_ALL_COMMENTS_FAIL';

export const VIEW_COMMENT_REQUEST = 'VIEW_COMMENT_REQUEST';
export const VIEW_COMMENT_SUCCESS = 'VIEW_COMMENT_SUCCESS';
export const VIEW_COMMENT_FAIL = 'VIEW_COMMENT_FAIL';

export const UPDATE_COMMENT_REQUEST = 'UPDATE_COMMENT_REQUEST';
export const UPDATE_COMMENT_SUCCESS = 'UPDATE_COMMENT_SUCCESS';
export const UPDATE_COMMENT_FAIL = 'UPDATE_COMMENT_FAIL';

export const COMMENT_DELETE_REQUEST = 'COMMENT_DELETE_REQUEST';
export const COMMENT_DELETE_SUCCESS = 'COMMENT_DELETE_SUCCESS';
export const COMMENT_DELETE_FAIL = 'COMMENT_DELETE_FAIL';

export const FETCH_RATINGS_REQUEST = 'FETCH_RATINGS_REQUEST';
export const FETCH_RATINGS_SUCCESS = 'FETCH_RATINGS_SUCCESS';
export const FETCH_RATINGS_FAILURE = 'FETCH_RATINGS_FAILURE';

export const CLEAR_COMMENT_ERRORS = 'CLEAR_COMMENT_ERRORS';
