// inventoryConstants.js

export const CREATE_INVENTORY_REQUEST = 'CREATE_INVENTORY_REQUEST';
export const CREATE_INVENTORY_SUCCESS = 'CREATE_INVENTORY_SUCCESS';
export const CREATE_INVENTORY_FAIL = 'CREATE_INVENTORY_FAIL';

export const FETCH_INVENTORY_REQUEST = 'FETCH_INVENTORY_REQUEST';
export const FETCH_INVENTORY_SUCCESS = 'FETCH_INVENTORY_SUCCESS';
export const FETCH_INVENTORY_FAIL = 'FETCH_INVENTORY_FAIL';

export const GET_INVENTORY_DETAILS_REQUEST = 'GET_INVENTORY_DETAILS_REQUEST';
export const GET_INVENTORY_DETAILS_SUCCESS = 'GET_INVENTORY_DETAILS_SUCCESS';
export const GET_INVENTORY_DETAILS_FAIL = 'GET_INVENTORY_DETAILS_FAIL';

export const UPDATE_INVENTORY_REQUEST = 'UPDATE_INVENTORY_REQUEST';
export const UPDATE_INVENTORY_SUCCESS = 'UPDATE_INVENTORY_SUCCESS';
export const UPDATE_INVENTORY_FAIL = 'UPDATE_INVENTORY_FAIL';
export const UPDATE_INVENTORY_RESET = 'UPDATE_INVENTORY_RESET';

export const DELETE_INVENTORY_REQUEST = 'DELETE_INVENTORY_REQUEST';
export const DELETE_INVENTORY_SUCCESS = 'DELETE_INVENTORY_SUCCESS';
export const DELETE_INVENTORY_FAIL = 'DELETE_INVENTORY_FAIL';