export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAIL = 'GET_ORDERS_FAIL';

export const UPDATE_ORDER_STATUS_REQUEST = 'UPDATE_ORDER_STATUS_REQUEST';
export const UPDATE_ORDER_STATUS_SUCCESS = 'UPDATE_ORDER_STATUS_SUCCESS';
export const UPDATE_ORDER_STATUS_FAIL = 'UPDATE_ORDER_STATUS_FAIL';

export const GET_ALL_ORDERS_REQUEST = 'GET_ALL_ORDERS_REQUEST';
export const GET_ALL_ORDERS_SUCCESS = 'GET_ALL_ORDERS_SUCCESS';
export const GET_ALL_ORDERS_FAILURE = 'GET_ALL_ORDERS_FAILURE';

export const GET_ALL_ORDERS_FORADMIN_REQUEST = 'GET_ALL_ORDERS_FORADMIN_REQUEST';
export const GET_ALL_ORDERS_FORADMIN_SUCCESS = 'GET_ALL_ORDERS_FORADMIN_SUCCESS';
export const GET_ALL_ORDERS_FORADMIN_FAIL = 'GET_ALL_ORDERS_FORADMIN_FAIL';

export const COUNT_WEEKLY_SALES_REQUEST = 'COUNT_WEEKLY_SALES_REQUEST';
export const COUNT_WEEKLY_SALES_SUCCESS = 'COUNT_WEEKLY_SALES_SUCCESS';
export const COUNT_WEEKLY_SALES_FAIL = 'COUNT_WEEKLY_SALES_FAIL';

export const GET_ORDER_COUNT_REQUEST = 'GET_ORDER_COUNT_REQUEST';
export const GET_ORDER_COUNT_SUCCESS = 'GET_ORDER_COUNT_SUCCESS';
export const GET_ORDER_COUNT_FAIL = 'GET_ORDER_COUNT_FAIL';

export const GET_CANCELLED_ORDER_COUNT_REQUEST = 'GET_CANCELLED_ORDER_COUNT_REQUEST';
export const GET_CANCELLED_ORDER_COUNT_SUCCESS = 'GET_CANCELLED_ORDER_COUNT_SUCCESS';
export const GET_CANCELLED_ORDER_COUNT_FAIL = 'GET_CANCELLED_ORDER_COUNT_FAIL';