export const ADD_RATING_REQUEST = 'ADD_RATING_REQUEST';
export const ADD_RATING_SUCCESS = 'ADD_RATING_SUCCESS';
export const ADD_RATING_FAIL = 'ADD_RATING_FAIL';

export const GET_ALL_RATING_REQUEST = 'GET_ALL_RATING_REQUEST';
export const GET_ALL_RATING_SUCCESS = 'GET_ALL_RATING_SUCCESS';
export const GET_ALL_RATING_FAIL = 'GET_ALL_RATING_FAIL';


export const CLEAR_RATING_ERRORS = 'CLEAR_RATING_ERRORS';