export const PRE_VERIFY_SELLER_REQUEST = 'PRE_VERIFY_SELLER_REQUEST';
export const PRE_VERIFY_SELLER_SUCCESS = 'PRE_VERIFY_SELLER_SUCCESS';
export const PRE_VERIFY_SELLER_FAIL = 'PRE_VERIFY_SELLER_FAIL';

export const VERIFY_SELLER_REQUEST = 'VERIFY_SELLER_REQUEST';
export const VERIFY_SELLER_SUCCESS = 'VERIFY_SELLER_SUCCESS';
export const VERIFY_SELLER_FAIL = 'VERIFY_SELLER_FAIL';

export const REGISTER_SELLER_REQUEST = 'REGISTER_SELLER_REQUEST';
export const REGISTER_SELLER_SUCCESS = 'REGISTER_SELLER_SUCCESS';
export const REGISTER_SELLER_FAIL = 'REGISTER_SELLER_FAIL';

export const SELLER_LOGIN_REQUEST = 'SELLER_LOGIN_REQUEST';
export const SELLER_LOGIN_SUCCESS = 'SELLER_LOGIN_SUCCESS';
export const SELLER_LOGIN_FAIL = 'SELLER_LOGIN_FAIL';

export const GET_DETAILS_REQUEST = 'GET_DETAILS_REQUEST';
export const GET_DETAILS_SUCCESS = 'GET_DETAILS_SUCCESS';
export const GET_DETAILS_FAIL = 'GET_DETAILS_FAIL';

export const SELLER_LOGOUT_REQUEST = 'SELLER_LOGOUT_REQUEST';
export const SELLER_LOGOUT_SUCCESS = 'SELLER_LOGOUT_SUCCESS';
export const SELLER_LOGOUT_FAIL = 'SELLER_LOGOUT_FAIL';

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';
export const FORGOT_PASSWORD_RESET = 'FORGOT_PASSWORD_RESET';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const RESET_PASSWORD_RESET = 'RESET_PASSWORD_RESET';

export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAIL = 'UPDATE_PASSWORD_FAIL';
export const UPDATE_PASSWORD_RESET = 'UPDATE_PASSWORD_RESET';

export const UPDATE_SELLER_REQUEST = 'UPDATE_SELLER_REQUEST';
export const UPDATE_SELLER_SUCCESS = 'UPDATE_SELLER_SUCCESS';
export const UPDATE_SELLER_FAIL = 'UPDATE_SELLER_FAIL';
export const UPDATE_SELLER_RESET = 'UPDATE_SELLER_RESET';

export const GET_SELLERS_REQUEST = 'GET_SELLERS_REQUEST';
export const GET_SELLERS_SUCCESS = 'GET_SELLERS_SUCCESS';
export const GET_SELLERS_FAIL = 'GET_SELLERS_FAIL';

export const SELLER_CLEAR_ERRORS = 'SELLER_CLEAR_ERRORS';