export const PRE_VERIFY_SELLER_REQUEST = 'PRE_VERIFY_SELLER_REQUEST';
export const PRE_VERIFY_SELLER_SUCCESS = 'PRE_VERIFY_SELLER_SUCCESS';
export const PRE_VERIFY_SELLER_FAIL = 'PRE_VERIFY_SELLER_FAIL';

export const SELLER_LOGIN_REQUEST = 'SELLER_LOGIN_REQUEST';
export const SELLER_LOGIN_SUCCESS = 'SELLER_LOGIN_SUCCESS';
export const SELLER_LOGIN_FAIL = 'SELLER_LOGIN_FAIL';

export const SELLER_CLEAR_ERRORS = 'SELLER_CLEAR_ERRORS';